pub const BARREL_HEALTH: u32 = 5;

//

pub const OVERLOAD_ENEMY_REGULAR: f32 = 5.;

pub const OVERLOAD_PROJECTILE_IMPACT: f32 = 0.1;
pub const OVERLOAD_FIRE_IMPACT: f32 = 0.05;
pub const OVERLOAD_BURNING_BARREL: f32 = 0.25;
pub const OVERLOAD_EXPLOSION: f32 = 1.5;
